using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace SourceGenerators.EF.Generators;

/// <summary>
/// For every DbContext marked with <c>[GenerateEntities("schema.json")]</c>, reads the JSON
/// schema (which must be an AdditionalFile) and emits one entity class per definition, a
/// Fluent API configuration for it, and DbSet properties plus ApplyGeneratedConfiguration on
/// the context. Entities with "extends" enrich an existing partial class instead of declaring
/// a new one.
/// </summary>
[Generator]
public sealed class EntityGenerator : IIncrementalGenerator
{
	private const string AttributeNamespace = "SourceGenerators.EF.Generators";
	private const string AttributeName = "GenerateEntitiesAttribute";
	private const string AttributeFullName = AttributeNamespace + "." + AttributeName;

	private const string AttributeSource = $$"""
		// <auto-generated/>
		#nullable enable
		namespace {{AttributeNamespace}};

		/// <summary>Generates entity classes and DbSet properties for this DbContext from a JSON schema.</summary>
		[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
		internal sealed class {{AttributeName}} : global::System.Attribute
		{
		    /// <param name="schemaPath">
		    /// Path to the schema, relative to the file declaring the context. The file must be
		    /// included in the project as an &lt;AdditionalFiles&gt; item.
		    /// </param>
		    public {{AttributeName}}(string schemaPath) => SchemaPath = schemaPath;

		    public string SchemaPath { get; }
		}
		""";

	private static readonly DiagnosticDescriptor InvalidSchema = new(
		id: "EFGEN001",
		title: "Invalid entity schema",
		messageFormat: "Could not parse {0}: {1}",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor PropertyClash = new(
		id: "EFGEN002",
		title: "Property already defined",
		messageFormat: "Entity '{0}' declares property '{1}', which is already defined on type '{2}'. Remove it from the schema.",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor SchemaNotFound = new(
		id: "EFGEN003",
		title: "Entity schema file not found",
		messageFormat: "Schema '{0}' was not found among the project's AdditionalFiles; add <AdditionalFiles Include=\"{0}\" /> to the project",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor ContextNotPartial = new(
		id: "EFGEN004",
		title: "DbContext must be partial",
		messageFormat: "Class '{0}' must be declared 'partial' for DbSet properties to be generated",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor ExtendedTypeNotFound = new(
		id: "EFGEN005",
		title: "Extended type not found",
		messageFormat: "Type '{0}' referenced by \"extends\" was not found in the compilation; use its fully-qualified name",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor ExtendedTypeNotPartial = new(
		id: "EFGEN006",
		title: "Extended type must be partial",
		messageFormat: "Type '{0}' must be declared 'partial' to be enriched from the schema",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor RelationalNotReferenced = new(
		id: "EFGEN007",
		title: "Relational EF Core not referenced",
		messageFormat: "Entity '{0}' sets \"table\", which requires Microsoft.EntityFrameworkCore.Relational (normally brought in by a database provider package)",
		category: "EntityGenerator",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	/// <summary>Location data that survives incremental caching (Location itself holds a SyntaxTree reference).</summary>
	private sealed record LocationInfo(string Path, TextSpan Span, LinePositionSpan LineSpan)
	{
		public static LocationInfo From(Location loc) => new(loc.SourceTree?.FilePath ?? "", loc.SourceSpan, loc.GetLineSpan().Span);
		public Location ToLocation() => Location.Create(Path, Span, LineSpan);
	}

	/// <summary>A DbContext decorated with the attribute.</summary>
	private sealed record ContextTarget(string? Namespace, string Name, bool IsPartial, string SchemaPath, string DeclaringDir, LocationInfo AttributeLocation);

	/// <summary>A context paired with its schema file, if one matched.</summary>
	private sealed record ResolvedTarget(ContextTarget Context, string? SchemaFilePath, string? SchemaText);

	/// <summary>
	/// What the emitter needs to know about a type the schema references (a base type or an
	/// extended type), extracted from the compilation into an equatable shape.
	/// </summary>
	private sealed record TypeFacts(string MetadataName, bool Found, string? Namespace, string Name, bool IsPartial, EquatableArray<string> InstanceMembers);

	/// <summary>Everything the emit step needs; equatable so emission is skipped when nothing relevant changed.</summary>
	private sealed record EmitInput(ResolvedTarget Target, EquatableArray<TypeFacts> Types, bool HasRelational);

	private const string RelationalExtensionsName = "Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions";

	// Types that are reference types in C# and therefore need `= null!` when non-nullable.
	private static readonly HashSet<string> ReferenceTypes = new(StringComparer.Ordinal)
	{
		"string", "byte[]", "object",
	};

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Ship the attribute with the generator so the consumer needs no runtime reference.
		context.RegisterPostInitializationOutput(static ctx =>
			ctx.AddSource("GenerateEntitiesAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

		var contexts = context.SyntaxProvider.ForAttributeWithMetadataName(
			AttributeFullName,
			predicate: static (node, _) => node is ClassDeclarationSyntax,
			transform: static (ctx, ct) => ToContextTarget(ctx, ct));

		var jsonFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
			.Select(static (f, ct) => (f.Path, Text: f.GetText(ct)?.ToString()))
			.Collect();

		// Pair each context with its schema file.
		var resolved = contexts
			.Combine(jsonFiles)
			.Select(static (pair, _) => ResolveSchema(pair.Left, pair.Right));

		// Look up the types the schema references. This re-runs on every compilation change,
		// but produces an equatable record, so the emit step only runs when the schema, the
		// context, or one of the referenced types actually changed.
		var emitInputs = resolved
			.Combine(context.CompilationProvider)
			.Select(static (pair, ct) => new EmitInput(
				pair.Left,
				CollectTypeFacts(pair.Left, pair.Right, ct),
				HasRelational: pair.Right.GetTypeByMetadataName(RelationalExtensionsName) is not null));

		context.RegisterSourceOutput(emitInputs, static (spc, input) => Emit(spc, input));
	}

	private static ContextTarget ToContextTarget(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
	{
		var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
		var syntax = (ClassDeclarationSyntax)ctx.TargetNode;
		var attr = ctx.Attributes[0];

		var schemaPath = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0].Value as string : null;
		var attrLocation = attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation() ?? syntax.Identifier.GetLocation();

		return new ContextTarget(
			Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
			Name: symbol.Name,
			IsPartial: syntax.Modifiers.Any(SyntaxKind.PartialKeyword),
			SchemaPath: schemaPath ?? "",
			DeclaringDir: Path.GetDirectoryName(syntax.SyntaxTree.FilePath) ?? "",
			AttributeLocation: LocationInfo.From(attrLocation));
	}

	private static ResolvedTarget ResolveSchema(ContextTarget target, ImmutableArray<(string Path, string? Text)> files)
	{
		if (target.SchemaPath.Length == 0) return new ResolvedTarget(target, null, null);

		// Exact match: attribute path resolved against the directory of the declaring file.
		var expected = NormalizePath(Path.Combine(target.DeclaringDir, target.SchemaPath));
		foreach (var f in files)
		{
			if (string.Equals(NormalizePath(f.Path), expected, StringComparison.OrdinalIgnoreCase))
				return new ResolvedTarget(target, f.Path, f.Text);
		}

		// Fallback: any additional file whose path ends with the attribute path (e.g. "Schemas/app.json").
		var suffix = NormalizePath(target.SchemaPath).TrimStart('/');
		foreach (var f in files)
		{
			if (NormalizePath(f.Path).EndsWith("/" + suffix, StringComparison.OrdinalIgnoreCase))
				return new ResolvedTarget(target, f.Path, f.Text);
		}

		return new ResolvedTarget(target, null, null);
	}

	private static string NormalizePath(string path)
	{
		try { path = Path.GetFullPath(path); } catch { /* keep as-is for odd inputs */ }
		return path.Replace('\\', '/');
	}

	/// <summary>Resolves every base/extended type named in the schema to a <see cref="TypeFacts"/>.</summary>
	private static EquatableArray<TypeFacts> CollectTypeFacts(ResolvedTarget target, Compilation compilation, CancellationToken ct)
	{
		if (target.SchemaText is null) return default;

		SchemaModel schema;
		try { schema = SchemaModel.FromJson(target.SchemaText); }
		catch (FormatException) { return default; } // EFGEN001 is reported by Emit

		var names = new SortedSet<string>(StringComparer.Ordinal); // sorted => stable order => stable equality
		foreach (var entity in schema.Entities)
		{
			if (entity.Extends is not null) names.Add(entity.Extends);
			else if (EffectiveBaseType(schema, entity) is string b) names.Add(b);
		}

		var facts = ImmutableArray.CreateBuilder<TypeFacts>(names.Count);
		foreach (var name in names)
		{
			var symbol = compilation.GetTypeByMetadataName(name);
			if (symbol is null)
			{
				facts.Add(new TypeFacts(name, Found: false, null, name, false, default));
				continue;
			}

			var isPartial = symbol.DeclaringSyntaxReferences.Any(r =>
				r.GetSyntax(ct) is ClassDeclarationSyntax c && c.Modifiers.Any(SyntaxKind.PartialKeyword));

			facts.Add(new TypeFacts(
				name,
				Found: true,
				Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
				Name: symbol.Name,
				IsPartial: isPartial,
				InstanceMembers: CollectInstanceMembers(symbol)));
		}
		return new EquatableArray<TypeFacts>(facts.ToImmutable());
	}

	/// <summary>Names of all non-static properties and fields on the type and its ancestors (excluding object).</summary>
	private static EquatableArray<string> CollectInstanceMembers(INamedTypeSymbol type)
	{
		var names = new SortedSet<string>(StringComparer.Ordinal);
		for (var t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
		{
			foreach (var m in t.GetMembers())
			{
				if (m.IsStatic || m.IsImplicitlyDeclared) continue;
				if (m is IPropertySymbol or IFieldSymbol) names.Add(m.Name);
			}
		}
		return new EquatableArray<string>(names.ToImmutableArray());
	}

	/// <summary>Entity-level "baseType" wins (including an explicit null to opt out); otherwise the schema default.</summary>
	private static string? EffectiveBaseType(SchemaModel schema, EntityModel entity) =>
		entity.HasBaseTypeOverride ? entity.BaseType : schema.BaseType;

	private static void Emit(SourceProductionContext spc, EmitInput input)
	{
		var target = input.Target;
		var ctx = target.Context;
		var attrLocation = ctx.AttributeLocation.ToLocation();

		if (!ctx.IsPartial)
		{
			spc.ReportDiagnostic(Diagnostic.Create(ContextNotPartial, attrLocation, ctx.Name));
			return;
		}
		// Emitted even when the schema is broken, so the user's call to ApplyGeneratedConfiguration
		// keeps compiling and the only errors shown are the schema ones.
		var configurations = new List<string>();
		EmitEntities(spc, input, attrLocation, configurations);
		spc.AddSource($"{ctx.Name}.Configuration.g.cs", SourceText.From(EmitApplyConfiguration(ctx, configurations), Encoding.UTF8));
	}

	private static void EmitEntities(SourceProductionContext spc, EmitInput input, Location attrLocation, List<string> configurations)
	{
		var target = input.Target;
		var ctx = target.Context;

		if (target.SchemaText is null || target.SchemaFilePath is null)
		{
			spc.ReportDiagnostic(Diagnostic.Create(SchemaNotFound, attrLocation, ctx.SchemaPath));
			return;
		}

		SchemaModel schema;
		try
		{
			schema = SchemaModel.FromJson(target.SchemaText);
		}
		catch (FormatException ex)
		{
			spc.ReportDiagnostic(Diagnostic.Create(InvalidSchema, attrLocation, target.SchemaFilePath, ex.Message));
			return;
		}

		var types = input.Types.ToDictionary(t => t.MetadataName, StringComparer.Ordinal);
		var schemaText = SourceText.From(target.SchemaText);
		var entityNamespace = EntityNamespace(schema, ctx);
		var dbSets = new List<(string FullName, string SetName)>();

		foreach (var entity in schema.Entities)
		{
			string fullName;
			string? ns;
			if (entity.IsExtension)
			{
				var facts = types[entity.Extends!];
				if (!facts.Found)
				{
					spc.ReportDiagnostic(Diagnostic.Create(ExtendedTypeNotFound, attrLocation, entity.Extends));
					continue;
				}
				if (!facts.IsPartial)
				{
					spc.ReportDiagnostic(Diagnostic.Create(ExtendedTypeNotPartial, attrLocation, entity.Extends));
					continue;
				}

				ReportClashes(spc, entity, facts, target.SchemaFilePath, schemaText);
				spc.AddSource($"{ctx.Name}.{entity.Name}.g.cs", SourceText.From(EmitExtension(facts, entity), Encoding.UTF8));
				fullName = facts.MetadataName;
				ns = facts.Namespace;
			}
			else
			{
				var baseType = EffectiveBaseType(schema, entity);
				// An unresolved base type is left to the compiler, which reports CS0246 on the generated file.
				if (baseType is not null && types.TryGetValue(baseType, out var baseFacts) && baseFacts.Found)
					ReportClashes(spc, entity, baseFacts, target.SchemaFilePath, schemaText);

				spc.AddSource($"{ctx.Name}.{entity.Name}.g.cs", SourceText.From(EmitEntity(entityNamespace, baseType, entity), Encoding.UTF8));
				fullName = $"{entityNamespace}.{entity.Name}";
				ns = entityNamespace;
			}

			// Only entities with something to configure get a configuration, since applying one
			// also adds the entity to the model.
			if (entity.Table is not null && !input.HasRelational)
			{
				spc.ReportDiagnostic(Diagnostic.Create(RelationalNotReferenced, attrLocation, entity.Name));
			}
			else if (entity.Table is not null || entity.Properties.Any(p => p.Key || p.Required || p.MaxLength is not null))
			{
				var configNamespace = ns is null ? "Configuration" : ns + ".Configuration";
				spc.AddSource($"{ctx.Name}.{entity.Name}Configuration.g.cs", SourceText.From(EmitConfiguration(configNamespace, fullName, entity), Encoding.UTF8));
				configurations.Add($"{configNamespace}.{entity.Name}Configuration");
			}

			if (entity.WantsDbSet)
				dbSets.Add((fullName, entity.Table ?? entity.Name + "s"));
		}

		if (dbSets.Count > 0)
			spc.AddSource($"{ctx.Name}.DbSets.g.cs", SourceText.From(EmitDbContext(ctx, dbSets), Encoding.UTF8));
	}

	/// <summary>Schema "namespace" if given, otherwise "&lt;ContextNamespace&gt;.Entities".</summary>
	private static string EntityNamespace(SchemaModel schema, ContextTarget ctx) =>
		schema.Namespace ?? (ctx.Namespace is null ? "Entities" : ctx.Namespace + ".Entities");

	private static void ReportClashes(SourceProductionContext spc, EntityModel entity, TypeFacts against, string schemaPath, SourceText schemaText)
	{
		var members = new HashSet<string>(against.InstanceMembers, StringComparer.Ordinal);
		foreach (var p in entity.Properties)
		{
			if (!members.Contains(p.Name)) continue;
			var location = LocateProperty(schemaPath, schemaText, entity.Extends ?? entity.Name, p.Name);
			spc.ReportDiagnostic(Diagnostic.Create(PropertyClash, location, entity.Name, p.Name, against.MetadataName));
		}
	}

	/// <summary>
	/// Best-effort location of a property's "name" value inside the schema so the error is
	/// clickable. Searches for the property name after the entity's own name.
	/// </summary>
	private static Location LocateProperty(string path, SourceText text, string entityName, string propertyName)
	{
		var raw = text.ToString();
		var entityIdx = raw.IndexOf($"\"{entityName}\"", StringComparison.Ordinal);
		var needle = $"\"{propertyName}\"";
		var propIdx = raw.IndexOf(needle, entityIdx < 0 ? 0 : entityIdx, StringComparison.Ordinal);
		if (propIdx < 0) propIdx = 0;

		var span = new TextSpan(propIdx, propIdx == 0 ? 0 : needle.Length);
		return Location.Create(path, span, text.Lines.GetLinePositionSpan(span));
	}

	private static string EmitEntity(string entityNamespace, string? baseType, EntityModel entity)
	{
		var sb = new StringBuilder();
		AppendHeader(sb, entityNamespace);
		var inherits = baseType is null ? "" : $" : global::{baseType}";
		sb.AppendLine($"public partial class {entity.Name}{inherits}");
		sb.AppendLine("{");
		AppendProperties(sb, entity);
		sb.AppendLine("}");
		return sb.ToString();
	}

	/// <summary>
	/// Enriches an existing class. Accessibility and base type are deliberately omitted: a
	/// partial declaration may leave them out, and repeating them here would be one more
	/// thing to keep in sync with the hand-written half.
	/// </summary>
	private static string EmitExtension(TypeFacts type, EntityModel entity)
	{
		var sb = new StringBuilder();
		AppendHeader(sb, type.Namespace);
		sb.AppendLine($"partial class {type.Name}");
		sb.AppendLine("{");
		AppendProperties(sb, entity);
		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void AppendHeader(StringBuilder sb, string? ns)
	{
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		if (ns is not null) sb.AppendLine($"namespace {ns};").AppendLine();
	}

	private static void AppendProperties(StringBuilder sb, EntityModel entity)
	{
		foreach (var p in entity.Properties)
		{
			var isRef = ReferenceTypes.Contains(p.Type);
			var type = p.Nullable ? p.Type + "?" : p.Type;
			// Non-nullable reference types get `= null!` so the compiler doesn't warn about
			// uninitialized members; EF materializes them anyway.
			var init = !p.Nullable && isRef ? " = null!;" : "";
			sb.AppendLine($"    public {type} {p.Name} {{ get; set; }}{init}");
		}
	}

	/// <summary>
	/// Fluent configuration for one entity. Internal because the entity may be (an extended
	/// type keeps its hand-written accessibility), and a public class could not expose it.
	/// </summary>
	private static string EmitConfiguration(string configNamespace, string entityFullName, EntityModel entity)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Microsoft.EntityFrameworkCore; // fluent extension methods (HasMaxLength, ToTable, ...)");
		sb.AppendLine();
		sb.AppendLine($"namespace {configNamespace};").AppendLine();
		// Lets ApplyConfigurationsFromAssembly skip generated configurations when they are
		// applied separately through ApplyGeneratedConfiguration.
		sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{typeof(EntityGenerator).FullName}\", \"{typeof(EntityGenerator).Assembly.GetName().Version}\")]");
		sb.AppendLine($"internal sealed class {entity.Name}Configuration : global::Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<global::{entityFullName}>");
		sb.AppendLine("{");
		sb.AppendLine($"    public void Configure(global::Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<global::{entityFullName}> builder)");
		sb.AppendLine("    {");

		if (entity.Table is not null)
			sb.AppendLine($"        builder.ToTable(\"{entity.Table}\");");

		var keys = entity.Properties.Where(p => p.Key).Select(p => p.Name).ToList();
		if (keys.Count == 1)
			sb.AppendLine($"        builder.HasKey(e => e.{keys[0]});");
		else if (keys.Count > 1)
			sb.AppendLine($"        builder.HasKey(e => new {{ {string.Join(", ", keys.Select(k => "e." + k))} }});");

		foreach (var p in entity.Properties)
		{
			var chain = new StringBuilder();
			if (p.Required) chain.Append(".IsRequired()");
			if (p.MaxLength is int max) chain.Append($".HasMaxLength({max})");
			if (chain.Length > 0)
				sb.AppendLine($"        builder.Property(e => e.{p.Name}){chain};");
		}

		sb.AppendLine("    }");
		sb.AppendLine("}");
		return sb.ToString();
	}

	/// <summary>
	/// Always emitted (possibly empty) so the user's OnModelCreating compiles even while the
	/// schema has errors.
	/// </summary>
	private static string EmitApplyConfiguration(ContextTarget ctx, List<string> configurations)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		if (ctx.Namespace is not null) sb.AppendLine($"namespace {ctx.Namespace};").AppendLine();

		sb.AppendLine($"partial class {ctx.Name}");
		sb.AppendLine("{");
		sb.AppendLine("    /// <summary>Applies the configuration generated from the entity schema. Call it from OnModelCreating.</summary>");
		sb.AppendLine("    private static void ApplyGeneratedConfiguration(global::Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)");
		sb.AppendLine("    {");
		foreach (var config in configurations)
			sb.AppendLine($"        modelBuilder.ApplyConfiguration(new global::{config}());");
		sb.AppendLine("    }");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private static string EmitDbContext(ContextTarget ctx, List<(string FullName, string SetName)> dbSets)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Microsoft.EntityFrameworkCore;");
		sb.AppendLine();
		if (ctx.Namespace is not null) sb.AppendLine($"namespace {ctx.Namespace};").AppendLine();

		sb.AppendLine($"partial class {ctx.Name}");
		sb.AppendLine("{");
		foreach (var (fullName, setName) in dbSets)
			sb.AppendLine($"    public DbSet<global::{fullName}> {setName} => Set<global::{fullName}>();");
		sb.AppendLine("}");
		return sb.ToString();
	}
}
